AskForHelp page for OpenCall
InternetOfUs/developer pull request #11
Opened 2022-02-14 16:50 UTC by StefanoTavonatti

- Added the AskForHelp page in the Open Call category

2022-02-16 10:00 UTC, carlocaprini requested changes

2022-02-16 10:00 UTC, carlocaprini commented on docs/tech/usecase/ask-for-helpv2.md
> +```json
@StefanoTavonattiUH this does not look like a valid _json_: `”` are missing in the keys. Can you please fix this?

2022-02-16 10:00 UTC, carlocaprini commented on docs/tech/opencalls/ask-for-help.md
> +If you want to deploy an instance of the **AskForHelp Chatbot** in the context of an open call, first write an email to support@internetofus.eu. We will create a new instance of the bot and we will g
```suggestion
Open callers are provided with the possibility of leveraging the Ask4Help bot that has been developed in the context of the project. The bot will be configured and deployed by the team.

If you want to deploy an instance of the **AskForHelp Chatbot** in the context of an open call, first write an email to `support@internetofus.eu`. A new instance of the bot will be deployed and open callers will be provided with the following information:
```

2022-02-16 15:22 UTC, StefanoTavonattiUH commented on docs/tech/usecase/ask-for-helpv2.md
> +```json
@carlocaprini  ✅

2022-02-17 10:26 UTC, carlocaprini approved these changes

2022-02-17 10:26 UTC, merged