adding the documentation for Commons APIs.
InternetOfUs/developer pull request #15
Opened 2022-03-01 12:10 UTC by mdrodas

addding commons-apis.md and addding the corresponding link in sidebars.js

2022-03-02 11:30 UTC, carlocaprini requested changes

2022-03-02 11:30 UTC, carlocaprini commented on docs/platform/commons-apis.md
> +1. Commons APIs (and streambase) https://github.com/InternetOfUs/streambase
@mdrodas can you please use a markdown link?

2022-03-02 11:30 UTC, carlocaprini commented on docs/platform/commons-apis.md
> +1. WeNet Platform Documentation https://github.com/InternetOfUs/components-documentation
@mdrodas can you please use a markdown link?

2022-03-02 11:30 UTC, carlocaprini commented on docs/platform/commons-apis.md
> +Commons APIs manages streams of data that are pushed mainly from external aplications towards the WeNet Platform (example: the iLog application from the University of Trento).  This component interac
@mdrodas can you please include details for accessing and using the application? 🙏 It is available on the app stores? If not, how is is possible to get it?

2022-03-02 11:30 UTC, carlocaprini commented on docs/platform/commons-apis.md
> +1. Location (locationeventpertime)
@mdrodas the meaning of the labels inside the parenthesis is not clear to me. Can you please make it clearer? 🙏

2022-03-03 16:18 UTC, mdrodas commented
I added more details as requested.

2022-05-25 09:10 UTC, merged